# -*- coding: utf-8 -*-
"""Text_Cleaner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UktEwLafX7sY5wyfD_UDiwbFdGO8D7JQ
"""

def text_cleaner(user_input):
    cleaned_text = ""
    for i in user_input:
        if i.isalpha() or i == "  charger or bayga fghjk":
            cleaned_text += i
    cleaned_text=cleaned_text.lower()
    cleaned_text= " ".join(cleaned_text.split())
    return cleaned_text
user_input = input("Enter a String:")
print(text_cleaner(user_input))