# -*- coding: utf-8 -*-
"""TP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16XhXLfPywLJUBcLy8ft7N7so68wgK_2M
"""

#!/usr/bin/env python
import re, random, math, collections, itertools

PRINT_ERRORS=1

#------------- Function Definitions ---------------------


def readFiles(sentimentDictionary,sentencesTrain,sentencesTest,sentencesNokia):

    #reading pre-labeled input and splitting into lines
    posSentences = open('rt-polarity.pos', 'r', encoding="ISO-8859-1")
    posSentences = re.split(r'\n', posSentences.read())

    negSentences = open('rt-polarity.neg', 'r', encoding="ISO-8859-1")
    negSentences = re.split(r'\n', negSentences.read())

    posSentencesNokia = open('nokia-pos.txt', 'r')
    posSentencesNokia = re.split(r'\n', posSentencesNokia.read())

    negSentencesNokia = open('nokia-neg.txt', 'r', encoding="ISO-8859-1")
    negSentencesNokia = re.split(r'\n', negSentencesNokia.read())

    posDictionary = open('positive-words.txt', 'r', encoding="ISO-8859-1")
    posWordList = [] # edit this to get the list of the positive sentiment words in the dictionary
    for word in posDictionary:
        word=word.strip()
        if word and not word.startswith(","):
          posWordList.append(word)


    negDictionary = open('negative-words.txt', 'r', encoding="ISO-8859-1")
    negWordList = [] # edit this to get the list of the negative sentiment words in the dictionary
    for word in negDictionary:
        word=word.strip()
        if word and not word.startswith(","):
         negWordList.append(word)

    for i in posWordList:
        sentimentDictionary[i] = 1
    for i in negWordList:
        sentimentDictionary[i] = -1

    # Create Training and Test Datsets:
    # We want to test on sentences we haven't trained on,
    # to see how well the model generalses to previously unseen sentences

    # create 90-10 split of training and test data from movie reviews, with sentiment labels
    for i in posSentences:
        if random.randint(1,10)<2:
            sentencesTest[i]="positive"
        else:
            sentencesTrain[i]="positive"

    for i in negSentences:
        if random.randint(1,10)<2:
            sentencesTest[i]="negative"
        else:
            sentencesTrain[i]="negative"

    # create Nokia Datset:
    for i in posSentencesNokia:
            sentencesNokia[i]="positive"
    for i in negSentencesNokia:
            sentencesNokia[i]="negative"

#----------------------------End of data initialisation ----------------#

# calculates p(W|Positive), p(W|Negative) and p(W) for all words in training data
def trainBayes(sentencesTrain, pWordPos, pWordNeg, pWord):
    posFeatures = [] # [] initialises a list [array]
    negFeatures = []
    freqPositive = {} # {} initialises a dictionary [hash function]
    freqNegative = {}
    dictionary = {}
    posWordsTot = 0
    negWordsTot = 0
    allWordsTot = 0

    # iterate through each sentence/sentiment pair in the training data
    for sentence, sentiment in sentencesTrain.items():
        wordList = re.findall(r"[\w']+", sentence)

        for word in wordList: # calculate over unigrams
            allWordsTot += 1 # keeps count of total words in dataset
            if not (word in dictionary):
                dictionary[word] = 1
            if sentiment=="positive" :
                posWordsTot += 1 # keeps count of total words in positive class

                # keep count of each word in positive context
                if not (word in freqPositive):
                    freqPositive[word] = 1
                else:
                    freqPositive[word] += 1
            else:
                negWordsTot+=1 # keeps count of total words in negative class

                # keep count of each word in positive context
                if not (word in freqNegative):
                    freqNegative[word] = 1
                else:
                    freqNegative[word] += 1

    for word in dictionary:
        # do some smoothing so that minimum count of a word is 1
        if not (word in freqNegative):
            freqNegative[word] = 1
        if not (word in freqPositive):
            freqPositive[word] = 1

        # Calculate p(word|positive)
        pWordPos[word] = freqPositive[word] / float(posWordsTot)

        # Calculate p(word|negative)
        pWordNeg[word] = freqNegative[word] / float(negWordsTot)

        # Calculate p(word)
        pWord[word] = (freqPositive[word] + freqNegative[word]) / float(allWordsTot)

#---------------------------End Training ----------------------------------

# implement naive bayes algorithm
# INPUTS:
#   sentencesTest is a dictonary with sentences associated with sentiment
#   dataName is a string (used only for printing output)
#   pWordPos is dictionary storing p(word|positive) for each word
#      i.e., pWordPos["apple"] will return a real value for p("apple"|positive)
#   pWordNeg is dictionary storing p(word|negative) for each word
#   pWord is dictionary storing p(word)
#   pPos is a real number containing the fraction of positive reviews in the dataset

def cal_accurracy(correct, total):
    return correct / total if total !=0  else 0

def cal_precision(correct_pos, total_pos_pred):
    return correct_pos / total_pos_pred if total_pos_pred !=0 else 0

def calculate_recall(correct_pos, total_pos):
    return correct_pos / total_pos if total_pos != 0 else 0

def calculate_f1_score(precision_pos, recall_pos):
    return (2 * precision_pos * recall_pos) / (precision_pos + recall_pos) if (precision_pos + recall_pos) > 0 else 0
def testBayes(sentencesTest, dataName, pWordPos, pWordNeg, pWord,pPos):

    print("Naive Bayes classification")
    pNeg=1-pPos

    # These variables will store results
    total=0
    correct=0
    totalpos=0
    totalpospred=0
    totalneg=0
    totalnegpred=0
    correctpos=0
    correctneg=0

    # for each sentence, sentiment pair in the dataset
    for sentence, sentiment in sentencesTest.items():
        wordList = re.findall(r"[\w']+", sentence)#collect all words

        pPosW=pPos
        pNegW=pNeg

        for word in wordList: # calculate over unigrams
            if word in pWord:
                if pWord[word]>0.00000001:
                    pPosW *=pWordPos[word]
                    pNegW *=pWordNeg[word]

        prob=0;
        if pPosW+pNegW >0:
            prob=pPosW/float(pPosW+pNegW)


        total+=1
        if sentiment=="positive":
            totalpos+=1
            if prob>0.5:
                correct+=1
                correctpos+=1
                totalpospred+=1
            else:
                correct+=0
                totalnegpred+=1
                if PRINT_ERRORS:
                    print ("ERROR (pos classed as neg %0.2f):" %prob + sentence)
        else:
            totalneg+=1
            if prob<=0.5:
                correct+=1
                correctneg+=1
                totalnegpred+=1
            else:
                correct+=0
                totalpospred+=1
                if PRINT_ERRORS:
                    print ("ERROR (neg classed as pos %0.2f):" %prob + sentence)
    accuracy = cal_accurracy(correct, total)
    accuracy = round(accuracy * 100) / 100
    precisionPos = cal_precision(correctpos, totalpospred)
    precisionPos = round(precisionPos * 100) / 100
    recallPos = calculate_recall(correctpos, totalpos)
    recallPos = round(recallPos * 100) / 100
    f1Pos = calculate_f1_score(precisionPos, recallPos)
    recallPos = round(recallPos * 100) / 100
    f1Pos = round(f1Pos * 100) / 100

    precisionNeg = cal_precision(correctneg, totalnegpred)
    recallNeg = calculate_recall(correctneg, totalneg)
    f1Neg = calculate_f1_score(precisionNeg, recallNeg)

    # Print results
    print(f"Accuracy: {accuracy:.4f} ")
    print(f"Precision (Positive): {precisionPos:.4f}, Recall (Positive): {recallPos:.4f}, F1-Score (Positive): {f1Pos:.4f}")
    print(f"Precision (Negative): {precisionNeg:.4f}, Recall (Negative): {recallNeg:.4f}, F1-Score (Negative): {f1Neg:.4f}")


# TODO for Step 2: Add some code here to calculate and print: (1) accuracy; (2) precision and recall for the positive class;
# (3) precision and recall for the negative class; (4) F1 score;





# This is a simple classifier that uses a sentiment dictionary to classify
# a sentence. For each word in the sentence, if the word is in the positive
# dictionary, it adds 1, if it is in the negative dictionary, it subtracts 1.
# If the final score is above a threshold, it classifies as "Positive",
# otherwise as "Negative"
def cal_accurracy(correct, total):
    return correct / total if total > 0 else 0

def cal_precision(correct_pos, total_pos_pred):
    return correct_pos / total_pos_pred if total_pos_pred > 0 else 0

def calculate_recall(correct_pos, total_pos):
    return correct_pos / total_pos if total_pos > 0 else 0

def calculate_f1_score(precision_pos, recall_pos):
    return (2 * precision_pos * recall_pos) / (precision_pos + recall_pos) if (precision_pos + recall_pos) > 0 else 0

#Rule based classification

def modified_testDictionary(sentencesTest, dataName, sentimentDictionary, threshold):

    print("Dictionary-based classification")
    total = 0
    correct = 0
    totalpos = 0
    totalneg = 0
    totalpospred = 0
    totalnegpred = 0
    correctpos = 0
    correctneg = 0

    intensifiers = {
        "totally", "utterly", "absolutely", "incredibly", "highly", "too", "very",
        "really", "quite", "significantly", "fairly", "particularly", "super",
        "notably", "super", "crazy", "massively"
    }
    diminishers = {
        "hardly", "kinda", "marginally", "sort of", "a bit", "relatively", "a little",
        "barely", "moderately", "somewhat", "faintly", "almost", "rather",
        "negligible", "to a lesser context", "might", "could", "minimal", "in part",
        "seldom", "not much"
    }
    negations = {
        "neither", "no", "nor", "not", "none", "no one", "nowhere", "nobody",
        "wasn't", "hasn't", "haven't", "hadn't", "doesn't", "isn't", "aren't",
        "weren't", "can't", "cannot", "barely", "rarely", "scarcely"
    }

    for sentence, sentiment in sentencesTest.items():
        Words = re.findall(r"[\w']+", sentence)
        score = 0
        negate = False
        dim = False
        inten = False

        for word in Words:
            if word in negations:
                negate = True
                continue
            if word in diminishers:
                dim = True
                continue
            if word in intensifiers:
                inten = True
                continue

            if word in sentimentDictionary:
                word_score = sentimentDictionary[word]


                if negate:
                    word_score *= -1
                    negate = False


                if word in intensifiers:
                    word_score *= 2



                if word in diminishers:
                    word_score *= 0.5



                score += word_score



        total += 1
        if sentiment == "positive":
            totalpos += 1
            if score >= threshold:
                correct += 1
                correctpos += 1
                totalpospred += 1
            else:
                totalnegpred += 1
        else:
            totalneg += 1
            if score < threshold:
                correct += 1
                correctneg += 1
                totalnegpred += 1
            else:
                totalpospred += 1

    accuracy = cal_accurracy(correct, total)
    accuracy = round(accuracy * 100) / 100
    precisionPos = cal_precision(correctpos, totalpospred)
    precisionPos = round(precisionPos * 100) / 100
    recallPos = calculate_recall(correctpos, totalpos)
    recallPos = round(recallPos * 100) / 100
    f1Pos = calculate_f1_score(precisionPos, recallPos)
    recallPos = round(recallPos * 100) / 100
    f1Pos = round(f1Pos * 100) / 100

    precisionNeg = cal_precision(correctneg, totalnegpred)
    recallNeg = calculate_recall(correctneg, totalneg)
    f1Neg = calculate_f1_score(precisionNeg, recallNeg)


    print(f"Accuracy: {accuracy:.4f}")
    print(f"Precision (Positive): {precisionPos:.4f}, Recall (Positive): {recallPos:.4f}, F1-Score (Positive): {f1Pos:.4f}")
    print(f"Precision (Negative): {precisionNeg:.4f}, Recall (Negative): {recallNeg:.4f}, F1-Score (Negative): {f1Neg:.4f}")
# TODO for Step 5: Add some code here to calculate and print: (1) accuracy; (2) precision and recall for the positive class;
# (3) precision and recall for the negative class; (4) F1 score;




# Print out n most useful predictors
def mostUseful(pWordPos, pWordNeg, pWord, n):
    predictPower={}
    for word in pWord:
        if pWordNeg[word]<0.0000001:
            predictPower=1000000000
        else:
            predictPower[word]=pWordPos[word] / (pWordPos[word] + pWordNeg[word])

    sortedPower = sorted(predictPower, key=predictPower.get)
    head, tail = sortedPower[:n], sortedPower[len(predictPower)-n:]
    print ("NEGATIVE:")
    print (head)
    print ("\nPOSITIVE:")
    print (tail)
    pos_words =0
    neg_words =0
    for word in sentimentDictionary:
      if word in tail:
        pos_words+=1
      if word in head:
        neg_words+=1

    print("\nNumber of positive words:", pos_words)
    print("\nNumber of negative words:", neg_words)




#---------- Main Script --------------------------


sentimentDictionary={} # {} initialises a dictionary [hash function]
sentencesTrain={}
sentencesTest={}
sentencesNokia={}

#initialise datasets and dictionaries
readFiles(sentimentDictionary,sentencesTrain,sentencesTest,sentencesNokia)

pWordPos={} # p(W|Positive)
pWordNeg={} # p(W|Negative)
pWord={}    # p(W)

# build conditional probabilities using training data
trainBayes(sentencesTrain, pWordPos, pWordNeg, pWord)

# run naive bayes classifier on datasets
print("\nI NAIVE BAYES CLASSIFIER")
print("\n1.Films train Dataset")
testBayes(sentencesTrain,  "Films (Train Data, Naive Bayes)\t", pWordPos, pWordNeg, pWord,0.5)
print("\n2.Films test Dataset")
testBayes(sentencesTest,  "Films  (Test Data, Naive Bayes)\t", pWordPos, pWordNeg, pWord,0.5)
print("\n3.Nokia Dataset")
testBayes(sentencesNokia, "Nokia   (All Data,  Naive Bayes)\t", pWordPos, pWordNeg, pWord,0.7)



# run sentiment dictionary based classifier on datasets
print("\nII RULE BASED CLASSIFIER")
print("\n1.Films Dataset")
modified_testDictionary(sentencesTrain,  "Films (Train Data, Rule-Based)\t", sentimentDictionary, 1)
print("\n2.Films Dataset")
modified_testDictionary(sentencesTest,  "Films  (Test Data, Rule-Based)\t",  sentimentDictionary, 1)
print("\n3.Nokia Dataset")
modified_testDictionary(sentencesNokia, "Nokia   (All Data, Rule-Based)\t",  sentimentDictionary, 1)


# print most useful words
print(mostUseful(pWordPos, pWordNeg, pWord, 100))